name: Docker Build and Push

on:
  push:
    paths-ignore:
      - 'terraform/**'
    branches:
      - main

env:
  ECR_REPOSITORY_PATIENT: patient-service
  ECR_REPOSITORY_APPOINTMENT: appointment-service
  AWS_REGION: eu-west-2

jobs:
  build-and-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1


     - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Generate Unique Image Tag
        run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build and Push Docker Image for Appointment-service
        run: |
          cd services/appointment-service
          docker build -t appointment-service:$IMAGE_TAG .
          docker tag appointment-service:$IMAGE_TAG $ECR_REPO_APPOINTMENT:$IMAGE_TAG
          docker push $ECR_REPO_APPOINTMENT:$IMAGE_TAG

      - name: Build and Push Docker Image for Patient-service
        run: |
          cd services/patient-service
          docker build -t patient-service:$IMAGE_TAG .
          docker tag patient--service:$IMAGE_TAG $ECR_REPO_PATIENT:$IMAGE_TAG
          docker push $ECR_REPO_PATIENT:$IMAGE_TAG

    # - name: Build, tag, and push patient-service image
    #   run: |
    #     docker build -t $ECR_REPOSITORY_PATIENT:latest -f services/Dockerfile-appoint ./apps
    #     docker tag $ECR_REPOSITORY_PATIENT:latest 412381761490.dkr.ecr.eu--west-2.amazonaws.com/$ECR_REPOSITORY_PATIENT:latest
    #     docker push 412381761490.dkr.ecr.eu-west-2.amazonaws.com/$ECR_REPOSITORY_PATIENT:latest

    # - name: Build, tag, and push appointment-service image
    #   run: |
    #     docker build -t $ECR_REPOSITORY_APPOINTMENT:latest -f apps/Dockerfile-patient ./apps
    #     docker tag $ECR_REPOSITORY_APPOINTMENT:latest 985539789378.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY_APPOINTMENT:latest
    #     docker push 985539789378.dkr.ecr.us-east-1.amazonaws.com/$ECR_REPOSITORY_APPOINTMENT:latest